version: 2.1

jobs:
  terraform_apply:
    docker:
      - image: hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: Terraform Plan
          command: |
            cd terraform
            terraform init
            terraform plan -out=terraform.plan
      - run:
          name: Terraform Apply
          command: |
            cd terraform
            terraform apply -auto-approve terraform.plan

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - terraform_apply